
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook
    env: lab
spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 2
  template:
    metadata:
      name: fb-pod
      labels:
        env: lab
        app: facebook
        version: v1-ac
    spec:
      containers:
        - name: fb-pod-container
          image: karthik970/b16:mindcircuit16d
          ports:
            - containerPort: 8080
