
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook
    env: lab
spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 3 
  template:
    metadata:
      name: fb-pod
      labels:
        env: lab
        app: facebook
        version: v1-ac
    spec:
      containers:
        - name: fb-pod-container
          image: sravani2310/mcapp:latest
          ports:
            - containerPort: 8080
